name: Deploy brand site

on:
  release:
    types:
      - released

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest

    # Set node version.
    steps:
      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.3"

      # Check out repo.
      - name: Checkout
        uses: actions/checkout@v2

      # Update package.json and package-lock.json with new version.
      - name: Update package files
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "Github Actions"
          tag=${{ github.events.release.tag_name }}
          version="${tag:1}"
          npm --no-git-tag-version version $version
          git status
          git add package.json package-lock.json
          git commit -m "Updating package files to reflect new version $version."
          git status
          git push
          git status

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Mock deploy
    steps:
      - name: Deploy
        run: |
          echo "The brand site was deployed."
