name: Open pull request

env:
  GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  repository_dispatch:
    types: [ elementish-pr-opened ]

jobs:
  open-pr:
    runs-on: ubuntu-latest
    env:
      GIT_USER: ${{ github.event.client_payload.actor }}
      FEATURE_BRANCH: ${{ github.event.client_payload.feature-branch }}
      COMMIT_MESSAGE: ${{ github.event.client_payload.commit-message }}

    steps:
      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.3"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "$GIT_SSH_KEY"

      - name: Point to Elementish feature branch
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "Github Actions"
          npm install elementish@git+ssh://git@github.com/rohnjeynolds/elementish.git#${{ env.FEATURE_BRANCH }}

      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: package.json,package-lock.json
          commit-message: "(Elementish) ${{ env.COMMIT_MESSAGE }}"
          committer: "Github Actions <github-actions@github.com>"
          author: "${{ env.GIT_USER }}"
          branch: "${{ env.FEATURE_BRANCH }}"
          base: main
          title: "Using Elementish branch ${{ env.FEATURE_BRANCH }}."
