name: Update feature branch

env:
  GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  repository_dispatch:
    types: [ element-feature-branch-updated ]

jobs:
  use-new-version:
    runs-on: ubuntu-latest
    env:
      GIT_USER: ${{ github.event.client_payload.actor }}
      FEATURE_BRANCH: ${{ github.event.client_payload.feature-branch }}

    steps:
      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.3"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.FEATURE_BRANCH }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "$GIT_SSH_KEY"

      - name: Use new version
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "Github Actions"
          npm install elementish@git+ssh://git@github.com/rohnjeynolds/elementish.git#${{ env.FEATURE_BRANCH }}
          git add package.json package-lock.json
          git commit -m "New commits on Elementish branch ${{ env.FEATURE_BRANCH }}."
